name: mqttapi
description: Minimal MQTT API implementation
version: 0.0.1
author:
homepage:

environment:                                                            
  sdk: '>=2.10.0 <3.0.0'    

dependencies:
  mqtt_client: ^7.2.1
  uuid: 2.0.4
  args: ^2.1.0  

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
